[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "20"
  NPM_FLAGS = "--force"
  NPM_CONFIG_PRODUCTION = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
